### ISSUE TITLE
DataSource埋点接入配置问题

### ISSUE THREAD

**Issue by xingguang2013** [alipay/sofa-tracer#159]
### DataSource埋点接入，测试发现只有xml方式配置数据源才能生效

在尝试使用DataSource埋点时，发现插件只能处理使用xml配置数据源的方式，如果使用Spring Boot原生的方式，也就是在application.yml文件直接配置某种数据源或时Java Config方式均不能使DataSouce埋点生效。

### 配置如下

1. Spring Boot原生方式(**埋点不生效**)：application.yml

```yml
spring:
  application:
    name: sofa-sample
  datasource:
      url: jdbc:mysql://localhost:3306/sofa
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: xxxx
      password: xxxx
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 3
        maximum-pool-size: 5
        idle-timeout: 30000
        pool-name: SofaHikariCPDatasource
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
```

2. Java Config方式(**埋点不生效**)

```java
@Configuration
public class DatasourceConfig {

    @Value("${spring.datasource.url}")
    private String jdbcUrl;

    @Value("${spring.datasource.driver-class-name}")
    private String driverClassName;

    @Value("${spring.datasource.username}")
    private String username;

    @Value("${spring.datasource.password}")
    private String password;

    @Bean
    public DataSource hikariDataSource(){
        HikariDataSource dataSource = new HikariDataSource();
        dataSource.setJdbcUrl(jdbcUrl);
        dataSource.setDriverClassName(driverClassName);
        dataSource.setUsername(username);
        dataSource.setPassword(password);
        return dataSource;
    }
}
```

3、Xml方式配置数据源(**埋点生效**)

application.yml

```yaml
spring:
  application:
    name: sofa-sample
  datasource:
      url: jdbc:mysql://localhost:3306/sofa
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: xxxx
      password: xxxx
```

datasouce.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
    <!-- dataSource pool -->
    <bean id="simpleDataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close" primary="true">
        <property name="driverClassName" value="${spring.datasource.driver-class-name}"/>
        <property name="jdbcUrl" value="${spring.datasource.url}"/>
        <property name="username" value="${spring.datasource.username}"/>
        <property name="password" value="${spring.datasource.password}"/>
    </bean>
</beans>
```

xml 配置

```java
@Configuration
@ImportResource(locations = {"classpath:/datasource.xml"})
public class DatasourceConfig {
    
}

```

### 建议

从插件代码看，是`com.alipay.sofa.tracer.boot.datasource.processor.DataSourceBeanFactoryPostProcessor`在处理数据源的代理，根据`BeanDefinition#getBeanClassName`的方法来判断数据源类型，可惜`Java Config`方式或`Spring Boot`原生方式没有获取到相关信息，导致无法初始化数据源代理。

### Environment

- SOFATracer version: 3.0.2
- JVM version : 1.8.0_171
- OS version : Windows 10
- Maven version: 3.5.4
- IDE version: IDEA 2018
